In [1]:
import numpy as np
import pandas as pd
import board_ops as b
import torch

In [2]:
#testing winning moves (and implicitly check_winner)
board1 = np.zeros((3, 3))
player1 = 1
player2 = -1
# print(b.winning_moves(board1, player1, 3))

board2 = np.array([[1, 1, 0], [-1, -1, 0], [1, 1, 0]])
# print(b.winning_moves(board2, player1, 3))
# print(b.winning_moves(board2, player2, 3))

board3 = np.array([[1, 0, 0], [0, -1, 0], [0, 1, 0], [0, 0, 0]])
print(board3)
# print(b.winning_moves(board3, player1, 2))
# print(b.winning_moves(board3, player2, 2))


[[ 1  0  0]
 [ 0 -1  0]
 [ 0  1  0]
 [ 0  0  0]]


In [3]:
b.get_valid_moves(board3)

[(0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 2), (3, 0), (3, 1), (3, 2)]

In [4]:
board4 = np.array([[1, -1, -1,], [0, 1, 0], [0, 0, 0]])
b.optimal_moves(board4, player1, 3)

(2, 2)

In [5]:
bb_arr = np.array([[[1, -1,], [-1, 0]], [[1, 1], [1, 1]], [[0, 0], [0, 0]]])
board_batch_1 = torch.tensor(bb_arr)
for i in bb_arr:
    print(i)
b.batch_board_full(board_batch_1)

[[ 1 -1]
 [-1  0]]
[[1 1]
 [1 1]]
[[0 0]
 [0 0]]


tensor([False,  True, False])

In [6]:
bb_arr_2 = np.array([[[1, -1,], [-1, 0]], [[1, 1], [0, -1]], [[0, 0], [0, 0]]])
board_batch_2 = torch.tensor(bb_arr_2)

b.batch_check_winner(board_batch_2, 2)

tensor([-1,  1,  0])

In [7]:
bb_arr_3 = boards = np.array([
    # Horizontal Wins
    [[ 0,  1,  0],  # Player 1 wins (horizontal)
     [ 0,  0,  0],
     [-1,  0,  1],
     [ 0, -1,  0],
     [ 1,  1,  1]],

    [[-1, -1, -1],  # Player -1 wins (horizontal)
     [ 0,  1,  0],
     [ 0,  0,  0],
     [ 1,  0,  1],
     [ 0,  0,  0]],

    # Vertical Wins
    [[ 0, -1,  0],  # Player 1 wins (vertical)
     [ 1,  0,  1],
     [ 1, -1,  0],
     [ 1,  0, -1],
     [ 0,  0,  0]],

    [[ 1,  1,  0],  # Player -1 wins (vertical)
     [ 0,  0,  1],
     [-1, -1,  0],
     [ 1, -1,  0],
     [ 0, -1,  1]],

    # Forward Diagonal Wins (\\)
    [[ 1,  0, -1],  # Player 1 wins (forward diagonal)
     [ 0,  1,  0],
     [-1,  0,  1],
     [ 0, -1,  0],
     [ 0,  0,  0]],

    [[ 0,  0,  1],  # Player -1 wins (forward diagonal)
     [-1, -1,  0],
     [ 1, -1, -1],
     [ 0,  1, -1],
     [ 0,  0,  0]],

    # Backward Diagonal Wins (/)
    [[ 0,  0, -1],  # Player 1 wins (backward diagonal)
     [ 0,  1,  1],
     [ 1,  1, -1],
     [ 1,  0,  1],
     [ 0,  0,  0]],

    [[ 0, -1,  0],  # Player -1 wins (backward diagonal)
     [-1,  0,  1],
     [ 1, -1, -1],
     [ 0, -1,  0],
     [-1,  0,  0]],

    # No Winner
    [[ 0,  0,  0],  # No winner
     [ 1, -1,  0],
     [-1,  1,  0],
     [ 0,  1, -1],
     [ 0,  0,  0]]
])
board_batch_3 = torch.tensor(bb_arr_3)

b.batch_check_winner(board_batch_3, 3)

tensor([ 1, -1,  1, -1,  1, -1,  1, -1,  0])

In [9]:
import os
data_dir = "data"
m, n, k = 3, 3, 3
train_data = np.load(os.path.join(data_dir,f"train_m{m}_n{n}_k{k}_all.npy")).astype(dtype=np.int64)
df1 = pd.DataFrame(train_data)
df1

0  1  2  3  4  5  6  7   8   9
0       9  2  8  5  7  1  0  3   4  10
1       9  8  0  5  2  7  6  1   4  10
2       9  0  4  2  7  8  5  1  10  10
3       9  4  2  3  5  1  6  0   7   8
4       9  3  0  6  5  2  8  1   4  10
...    .. .. .. .. .. .. .. ..  ..  ..
255163  9  1  5  2  0  6  4  3   8  10
255164  9  4  2  8  1  3  7  6   0  10
255165  9  0  8  6  7  4  5  3  10  10
255166  9  4  3  5  6  2  7  8  10  10
255167  9  0  4  6  3  1  8  2  10  10

[255168 rows x 10 columns]

In [ ]:
# df1 = df1.iloc[2:3].reset_index(drop=True)
df1

0  1  2  3  4  5   6   7   8   9
0      9  1  8  4  5  6   3   0   7   2
1      9  6  7  0  2  8   4   1   3   5
2      9  5  2  4  3  7   0   1  10  10
3      9  6  7  1  0  5   2   8   3   4
4      9  0  7  5  4  8   6   3   2  10
...   .. .. .. .. .. ..  ..  ..  ..  ..
99995  9  4  3  0  8  6   2   7   1   5
99996  9  6  4  7  2  5   1   0   8   3
99997  9  7  2  6  1  8  10  10  10  10
99998  9  0  8  2  5  3   7   1  10  10
99999  9  6  7  3  0  5   4   8   2   1

[100000 rows x 10 columns]

In [10]:
from benchmark_function import expected_loss_perfect_model
expected_loss_perfect_model(df1)

np.float64(1.40180239810089)

In [ ]:
x = float((df1.iloc[:, 8] == 10).mean())
x + 0.5*(1-x)

0.7239150000000001

In [ ]:
# from benchmark_function import benchmark
# benchmark(3, 3, 3, 1000, silent=True)